trigger:
  branches:
    include:
      - main
pool:
  vmImage: windows-latest
  - script: >
      curl -O
      https://downloads.lambdatest.com/hyperexecute/windows/hyperexecute.exe

      hyperexecute.exe -u $anubhas -k $JvGShZ2Bm8RdgmGFbbx4ZtbOb6DeQ8nqSvtHDZdDY7PzqaZMTq -i matrix.yaml
    displayName: Download and Run hyperexecute
